---
swagger: "2.0"
info:
  description: "This is the documentation for COLOR BLOCKS, built by Swagger UI."
  version: "1.0.1"
  title: "COLOR BLOCKS"
  contact:
    url: "https://discordapp.com/users/642482712560533515"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "Names"
  description: "Objects detected and used via their names"
schemes:
- "https"
- "http"
paths:
  DamageBlock:
    post:
      tags:
      - "Names"
      summary: "Damages the player. "
      description: "Damages a player on contact. (1) argument."
      operationId: "DamageBlock"
  
definitions:
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
